import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState("");
  const [isValid, setIsValid] = useState(true);
  const submitHandler = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email)) {
      fetch(`https://jsonplaceholder.typicode.com/posts`, {
        method: "POST",
        body: JSON.stringify({
          email,
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      }).then((res) => {
        setEmail("");
        console.log("Subscrbed");
      });
    } else {
      console.log("invalid email");
      setIsValid(false);
    }
  };
  return (
    <>
      <Head>
        <title>Coming Soon</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        className={`${inter.className} bg-gradient-to-br from-indigo-600 gap-8 px-4 md:px-0 to-indigo-800 min-h-screen flex flex-col items-center justify-center`}
      >
        <h1 className='text-3xl md:text-7xl font-semibold text-white'>
          We&apos;re Coming Soon
        </h1>
        <form onSubmit={submitHandler} className='flex gap-4 flex-wrap'>
          <input
            type='email'
            required
            value={email}
            onChange={(e) => setEmail(e.currentTarget.value)}
            className={`rounded-md px-2 placeholder:text-slate-500 focus:outline-none py-3 grow ${
              isValid ? "" : "ring-2 ring-red-500"
            }`}
            placeholder='Subscribe to newsletter'
          />
          <button className='bg-slate-900 text-white px-8 py-3 mx-auto rounded-md hover:scale-105 transition-transform duration-300'>
            Submit
          </button>
        </form>
      </main>
    </>
  );
}
